export enum NotifyTipe {
  ADD_BOARD = 'ADD_BOARD',
  DELETE_BOARD = 'DELETE_BOARD',
  DELETE_BOARD_INNER = 'DELETE_BOARD_INNER',
  ADD_COLUMN = 'ADD_COLUMN',
  UPDATE_COLUMN = 'UPDATE_COLUMN',
  ADD_TASK = 'ADD_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
}
